version: '2'
services:
  postgres:
    build: postgres/
    ports:
    - 5432:5432
    restart: always

  web:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/journal

  front:
    build: ../journal-face/
    ports:
    - 4200:4200
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
